// Define the exact file structure that should be in the ZIP
export const TEMPLATE_FILE_STRUCTURE = [
  'site-settings.json',
  'manifest.json',
  'templates/2438.json',
  'templates/2218.json',
  'templates/2198.json',
  'templates/2168.json',
  'templates/1107.json',
  'templates/1098.json',
  'templates/230.json',
  'templates/227.json',
  'templates/87.json',
  'templates/28.json',
  'taxonomies/category.json',
  'taxonomies/post_tag.json',
  'taxonomies/nav_menu.json',
  'content/page/484.json',
  'content/page/466.json',
  'content/page/255.json',
  'content/page/45.json',
  'wp-content/post/post.xml',
  'wp-content/page/page.xml',
  'wp-content/nav_menu_item/nav_menu_item.xml'
];